
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-vs
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - route:
    - destination:
        host: demo-istio
        port:
          number: 80
